### ISSUE TITLE
【依頼】Protospace挙動確認

### ISSUE THREAD

**Issue by on102-yamauchi-kazuhiro** [on102-yamauchi-kazuhiro/protospace-35937#1]
#URL
https://protospace-35937.herokuapp.com/

**Comment by kohei-isoda** [comment]
@on102-yamauchi-kazuhiro  さん、ご提出ありがとうございます‼︎
全ての実装において正常に動作することが確認できましたのでLGTMです、おめでとうございます🎉

次はいよいよ最終課題ですね、今まで学習したことを活かして進めていきましょう！
別途、最終課題についてのご案内をチャンネルに送付させていただきます。今しばらくお待ちください。

**Comment by on102-yamauchi-kazuhiro** [comment]
ご確認ありがとうございました。

**Comment by on102-yamauchi-kazuhiro** [comment]
ご確認ありがとうございました。
